import Navbar from "@/components/navbar";
import { Open_Sans } from "next/font/google";
import './globals.css'
export const metadata = {
  title: "SimpleBlog",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <Navbar />
        <div className="container p-6">
          {children}
        </div>
      </body>
    </html>
  );
}
